### ISSUE TITLE
Yahoo Finance API no longer working

### ISSUE THREAD

**Issue by ohansrud** [sergiocormio/stock-alerts#1]
Is this still working? Getting an error message when I try to fetch stock quotes.

**Comment by sergiocormio** [comment]
Yes, It's still working using version 3.12.1 of Yahoo API. Please tell me the ticker that you're getting the error. Or paste here your stack trace. 
Regards.

**Comment by ohansrud** [comment]
Never mind. Something wrong in my Tomcat config :)
