### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by toxilate** [sergiocormio/stock-alerts#2]
Hey,

First off, thanks for sharing this. I'm looking forward to testing it out. However, I'm a bit lost getting it set up. I know a bit python but not much about java. Would you be able to give a noob a bit more detail for getting this set up and running? Would be much appreciated.

Also, you mentioned it uses the Yahoo Finance API. I was under the impression this was discontinued by Yahoo. Am I mistaken?

Thank you.

**Comment by toxilate** [comment]
I got it working. If anyone needs help feel free to message me.

**Comment by sergiocormio** [comment]
Great news my friend that it's working. Just let me a few days to complete a "setup guide for noobs". I'm on vacations right now and here, in Argentinian beaches, the internet is too slow... Yahoo API is working and there is an active project on GitHub to wrap the API in Java.
Some steps to configure stock alerts:
1. Install java jre on your operative system
2. Download an application server i.e. tomcat
3. Install maven
4. Download stock-alerts and compile it using maven
5. Deploy the binary on your application server
6. Take a look and change the application.properties
7. Start the application server
8. In a browser... go to localhost:8080/

**Comment by sergiocormio** [comment]
8. In a browser go to http://localhost:8080/stock-alerts and navigate the ui.

**Comment by toxilate** [comment]
Thanks Sergio! I'm actually having an issue that I was hoping you might be able to help with.

When creating alerts what is the difference between saving an alert and processing an alert? It seems I only get an email when I click process on a saved alert that the conditions are currently true. All saved alerts which the conditions are currently false do no process and I don't get an email. I also do not get an email when a saved alert satisfies the alert conditions. Not sure how to set the alerts up properly - Any further instruction you can give?

As well, I somehow saved an alert without an ID and I cannot delete it now. Where are these alerts saved so I can manually delete it from the file?

**Comment by sergiocormio** [comment]
I'm sorry for the lack of validations on the frontend. I'll be working on that. The correct steps to create an alert are:
1. Complete the alert form
2. Press save button
3. View and Choose the alert from the table
4. Click on Process button or wait until job scheduled everyday run.
There is a job that process every active alert and you can configure the schedule time via application properties.
All the alerts are stored in a single file that you can delete and start all over again. This file also is configurable in application.properties file.

**Comment by toxilate** [comment]
Thank you and no worries! Am I able to have the alerts email me in real-time instead of an end of the day digest? If so, how would I change that?

Where is that alert file stored for me to delete?

Cheers!
